#!/usr/bin/env bash

config_folder=config

if ! grep zsh_profile ~/.zshrc
then
    mkdir -p ~/backups
    cp ~/.zshrc ~/backups/zshrc 
    echo -e source `pwd`/$config_folder/zsh_profile "\n" >> ~/.zshrc
fi

ln -s `pwd`/$config_folder/vimrc ~/.vimrc
